/*
 * This source file was generated by the Gradle 'init' task
 */
package sco3.mcp;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.modelcontextprotocol.server.McpAsyncServer;
import io.modelcontextprotocol.server.McpServer;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.transport.StdioServerTransportProvider;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.Content;
import io.modelcontextprotocol.spec.McpSchema.ServerCapabilities;
import io.modelcontextprotocol.spec.McpSchema.Tool;
import reactor.core.publisher.Mono;

public class AppAsync {

	private static Logger logger = LoggerFactory.getLogger(App.class);

	public static void main(String[] args) {
		StdioServerTransportProvider tProvider = (//
		new StdioServerTransportProvider() //
		);

		var cap = ServerCapabilities.builder() //
				.tools(true) //
				.logging() //
				.build();

		McpAsyncServer server = McpServer//
				.async(tProvider)//
				.serverInfo("my-server", "1.0.0")//
				.capabilities(cap)//
				.build();

		var schema = """
				{
				  "type" : "object",
				  "properties" : {
				    "a" : {
				      "type" : "number"
				    },
				    "b" : {
				      "type" : "number"
				    }
				  }
				}
				""";

		var tool = new McpServerFeatures.AsyncToolSpecification(//
				new Tool("mux", "mux", schema), //
				(exchange, arguments) -> {
					List<Content> list = List.of(new McpSchema.TextContent(""));
					System.out.println(list);

					return Mono.just(new McpSchema.CallToolResult(List.of(new McpSchema.TextContent("0")), null));

				});

		logger.info("""
				{"jsonrpc":"2.0","id":1,"method":"notifications/tools/list_changed"}
				""".replaceAll("\n", ""));

		server.addTool(tool).subscribe();

	}
}
